export const OWNER_ACCESS = 'OWNER_ACCESS'
export const ADMIN_ACCESS = 'ADMIN_ACCESS'
export const EDIT_ACCESS = 'EDIT_ACCESS'
export const VIEW_ACCESS = 'VIEW_ACCESS'

export const ORG_OWNER_ACCESS = 'ORG_OWNER_ACCESS'
export const ORG_ADMIN_ACCESS = 'ORG_ADMIN_ACCESS'
export const ORG_MEMBER_ACCESS = 'ORG_MEMBER_ACCESS'
