export const CHILDREN = 'lib:children'
export const PROPERTY_ID = 'lib:childId'
export const REQUIRED = 'lib:required'
export const IS_MULTIPLE = 'lib:isMultiple'
export const REGEX = 'lib:regex'
export const MIN_LENGTH = 'lib:minLength'
export const MAX_LENGTH = 'lib:maxLength'
export const MIN = 'lib:min'
export const MAX = 'lib:max'

export const BOOLEAN = 'lib:Boolean'
export const TEXT = 'lib:Text'
export const ENUM = 'lib:Enum'
export const URL = 'lib:Url'
export const EMAIL = 'lib:Email'
export const HOSTNAME = 'lib:Hostname'

export const DATE = 'lib:Date'
export const DATE_TIME = 'lib:DateTime'
export const TIME = 'lib:Time'

export const NUMBER = 'lib:Number'
export const INTEGER = 'lib:Integer'
export const INTEGER_8 = 'lib:Int8'
export const INTEGER_16 = 'lib:Int16'
export const INTEGER_32 = 'lib:Int32'
export const INTEGER_64 = 'lib:Int64'

export const FLOAT_32 = 'lib:Float32'
export const FLOAT_64 = 'lib:Float64'
